### PR TITLE
godaddy: allow parallel solve.

### LINKED ISSUE #1113: Unable to obtain wildcard certificate with DNS challenge using Go Daddy
Hello there. I'm opening up this issue coming from this one from Traefik: https://github.com/containous/traefik/issues/6686

When I try to get a wildcard certificate with GoDaddy, I get the following error:

> traefik | time="2020-04-16T10:24:59Z" level=error msg="Unable to obtain ACME certificate for domains "example.org,*.example.org" : unable to generate a certificate for the domains [example.org *.example.org]: acme: Error -> One or more domains had a problem:\n[example.org] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: During secondary validation: Incorrect TXT record "null" found at _acme-challenge.example.org, url: \n" providerName=wildcard-godaddy.acme

It seems like it is a lego problem with GoDaddy. Please find here below the traefik log related to this lego problem:

```
traefik    | time="2020-04-16T10:23:10Z" level=debug msg="legolog: [INFO] [example.org, *.example.org] acme: Obtaining bundled SAN certificate"
traefik    | time="2020-04-16T10:23:10Z" level=debug msg="legolog: [INFO] [*.example.org] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/<id1>"
traefik    | time="2020-04-16T10:23:10Z" level=debug msg="legolog: [INFO] [example.org] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/<id2>"
traefik    | time="2020-04-16T10:23:10Z" level=debug msg="legolog: [INFO] [*.example.org] acme: use dns-01 solver"
traefik    | time="2020-04-16T10:23:10Z" level=debug msg="legolog: [INFO] [example.org] acme: Could not find solver for: tls-alpn-01"
traefik    | time="2020-04-16T10:23:10Z" level=debug msg="legolog: [INFO] [example.org] acme: Could not find solver for: http-01"
traefik    | time="2020-04-16T10:23:10Z" level=debug msg="legolog: [INFO] [example.org] acme: use dns-01 solver"
traefik    | time="2020-04-16T10:23:10Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Preparing to solve DNS-01"
traefik    | time="2020-04-16T10:23:11Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Trying to solve DNS-01"
traefik    | time="2020-04-16T10:23:11Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Checking DNS record propagation using [127.0.0.11:53]"
traefik    | time="2020-04-16T10:23:11Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]"
traefik    | time="2020-04-16T10:23:11Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:13Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:15Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:17Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:19Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:21Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:23Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:25Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:27Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:29Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:31Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:33Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:23:43Z" level=debug msg="legolog: [INFO] [*.example.org] The server validated our request"
traefik    | time="2020-04-16T10:23:43Z" level=debug msg="legolog: [INFO] [*.example.org] acme: Cleaning DNS-01 challenge"
traefik    | time="2020-04-16T10:23:44Z" level=debug msg="legolog: [INFO] sequence: wait for 1m0s"
traefik    | time="2020-04-16T10:24:44Z" level=debug msg="legolog: [INFO] [example.org] acme: Preparing to solve DNS-01"
traefik    | time="2020-04-16T10:24:45Z" level=debug msg="legolog: [INFO] [example.org] acme: Trying to solve DNS-01"
traefik    | time="2020-04-16T10:24:45Z" level=debug msg="legolog: [INFO] [example.org] acme: Checking DNS record propagation using [127.0.0.11:53]"
traefik    | time="2020-04-16T10:24:45Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]"
traefik    | time="2020-04-16T10:24:45Z" level=debug msg="legolog: [INFO] [example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:24:47Z" level=debug msg="legolog: [INFO] [example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:24:49Z" level=debug msg="legolog: [INFO] [example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:24:51Z" level=debug msg="legolog: [INFO] [example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:24:53Z" level=debug msg="legolog: [INFO] [example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:24:55Z" level=debug msg="legolog: [INFO] [example.org] acme: Waiting for DNS record propagation."
traefik    | time="2020-04-16T10:24:58Z" level=debug msg="legolog: [INFO] [example.org] acme: Cleaning DNS-01 challenge"
traefik    | time="2020-04-16T10:24:58Z" level=debug msg="legolog: [INFO] Skipping deactivating of valid auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/<id1>"
traefik    | time="2020-04-16T10:24:58Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/<id2>"
traefik    | time="2020-04-16T10:24:59Z" level=debug msg="legolog: [INFO] Unable to deactivate the authorization: https://acme-v02.api.letsencrypt.org/acme/authz-v3/<id2>"
traefik    | time="2020-04-16T10:24:59Z" level=error msg="Unable to obtain ACME certificate for domains \"example.org,*.example.org\" : unable to generate a certificate for the domains [example.org *.example.org]: acme: Error -> One or more domains had a problem:\n[example.org] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: During secondary validation: Incorrect TXT record \"null\" found at _acme-challenge.example.org, url: \n" providerName=wildcard-godaddy.acme
```

### PR DESCRIPTION
**Pull request by ldez**
```console
$ ./lego -m email@example.com --dns godaddy -d *.example.org -d example.org -s https://acme-staging-v02.api.letsencrypt.org/directory run

2020/04/17 13:11:31 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2020/04/17 13:11:40 [INFO] acme: Registering account for email@example.com
!!!! HEADS UP !!!!

                Your account credentials have been saved in your Let's Encrypt
                configuration directory at "/home/ldez/sources/go/src/github.com/go-acme/lego/.lego/accounts".
                You should make a secure backup of this folder now. This
                configuration directory will also contain certificates and
                private keys obtained from Let's Encrypt so making regular
                backups of this folder is ideal.2020/04/17 13:11:41 [INFO] [*.example.org, example.org] acme: Obtaining bundled SAN certificate
2020/04/17 13:11:42 [INFO] [*.example.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/49829715
2020/04/17 13:11:42 [INFO] [example.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/49829716
2020/04/17 13:11:42 [INFO] [*.example.org] acme: use dns-01 solver
2020/04/17 13:11:42 [INFO] [example.org] acme: Could not find solver for: tls-alpn-01
2020/04/17 13:11:42 [INFO] [example.org] acme: Could not find solver for: http-01
2020/04/17 13:11:42 [INFO] [example.org] acme: use dns-01 solver
2020/04/17 13:11:42 [INFO] [*.example.org] acme: Preparing to solve DNS-01
2020/04/17 13:11:45 [INFO] [example.org] acme: Preparing to solve DNS-01
2020/04/17 13:11:46 [INFO] [*.example.org] acme: Trying to solve DNS-01
2020/04/17 13:11:46 [INFO] [*.example.org] acme: Checking DNS record propagation using [192.168.1.1:53]
2020/04/17 13:11:46 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2020/04/17 13:11:46 [INFO] [*.example.org] acme: Waiting for DNS record propagation.
2020/04/17 13:11:48 [INFO] [*.example.org] acme: Waiting for DNS record propagation.
2020/04/17 13:11:51 [INFO] [*.example.org] acme: Waiting for DNS record propagation.
2020/04/17 13:11:53 [INFO] [*.example.org] acme: Waiting for DNS record propagation.
2020/04/17 13:11:55 [INFO] [*.example.org] acme: Waiting for DNS record propagation.
2020/04/17 13:11:58 [INFO] [*.example.org] acme: Waiting for DNS record propagation.
2020/04/17 13:12:00 [INFO] [*.example.org] acme: Waiting for DNS record propagation.
2020/04/17 13:12:02 [INFO] [*.example.org] acme: Waiting for DNS record propagation.
2020/04/17 13:12:04 [INFO] [*.example.org] acme: Waiting for DNS record propagation.
2020/04/17 13:12:07 [INFO] [*.example.org] acme: Waiting for DNS record propagation.
2020/04/17 13:12:15 [INFO] [*.example.org] The server validated our request
2020/04/17 13:12:15 [INFO] [example.org] acme: Trying to solve DNS-01
2020/04/17 13:12:15 [INFO] [example.org] acme: Checking DNS record propagation using [192.168.1.1:53]
2020/04/17 13:12:15 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2020/04/17 13:12:23 [INFO] [example.org] The server validated our request
2020/04/17 13:12:23 [INFO] [*.example.org] acme: Cleaning DNS-01 challenge
2020/04/17 13:12:25 [INFO] [example.org] acme: Cleaning DNS-01 challenge
2020/04/17 13:12:26 [INFO] [*.example.org, example.org] acme: Validations succeeded; requesting certificates
2020/04/17 13:12:28 [INFO] [*.example.org] Server responded with a certificate.

```

Fix #1113

### CODE REVIEW

**Comment by dmke** [comment]
LGTM on a first glance. Will review later more thoroughly.

File: providers/dns/godaddy/client.go [hunk 1]
```diff
@@ -7,35 +7,64 @@ import (
...
-func (d *DNSProvider) updateRecords(records []DNSRecord, domainZone string, recordName string) error {
+func (d *DNSProvider) getRecords(domainZone string, rType string, recordName string) ([]DNSRecord, error) {
+	resource := path.Clean(fmt.Sprintf("/v1/domains/%s/records/%s/%s", domainZone, rType, recordName))
+
+	resp, err := d.makeRequest(http.MethodGet, resource, nil)
+	if err != nil {
+		return nil, err
+	}
+
+	defer func() { _ = resp.Body.Close() }()
```
Comment (wyattjoh) [inline providers/dns/godaddy/client.go:30]: This doesn't have any functional difference from:

```go
defer resp.Body.Close()
```

Is this because of linting?

Comment (ldez) [reply providers/dns/godaddy/client.go:30]: Currently, I prefer `defer func() { _ = something.Close() }()` due to the explicit ignore of the error.
It's a bit more verbose but it's mush easy to read and check ignored errors.

Comment (wyattjoh) [reply providers/dns/godaddy/client.go:30]: As a general rule of thumb, if that's the direction that lego should be moving, then I'd suggest seeing if it can be added as a linting rule. Specifically to ensure consistency throughout the rest of the codebase in the future. Just a recommendation!
