### PR TITLE
inwx: wait before generating new TOTP TANs

### LINKED ISSUE #1608: INWX: Issue when using 2FA - Same 2FA code is used twice when Present returns non-error
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

i should've seen that lego is presenting letsencrypt the dns challenge and that the challenge gets removed.

The removal does not work though which results in not downloading the certificate.

### What did you see instead?

Output:
```
cleaning up failed: inwx: (2200) Authentication error. Reason: (INVALID) The confirmation code is invalid.
```
Unless you are lucky and your `Present` is called in one 30s timeframe and your `CleanUp` is called in the next 30s timeframe the same 2FA code gets used twice (which is not a valid case for 2FA and most systems seem to implement it correctly).

### How do you use lego?

Docker image

### Reproduction steps

* have a inwx account
* enable 2fa
* try to get a wildcard certificate:
```
docker run -v certs:/lego -w /lego -e INWX_USERNAME=a -e INWX_PASSWORD=b -e INWX_SHARED_SECRET=c  goacme/lego:v4.6.0 -m your-mail@gmail.com --dns inwx -d example.de -d '*.example.de' -a --path /lego --pem run
```

### Version of lego

```console
4.6.0
```

### Logs

<details>

```console
2022/03/20 17:34:21 [INFO] [example.de, *.example.de] acme: Obtaining bundled SAN certificate
2022/03/20 17:34:22 [INFO] [*.example.de] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/12345
2022/03/20 17:34:22 [INFO] [example.de] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/12345
2022/03/20 17:34:22 [INFO] [example.de] acme: authorization already valid; skipping challenge
2022/03/20 17:34:22 [INFO] [*.example.de] acme: use dns-01 solver
2022/03/20 17:34:22 [INFO] [*.example.de] acme: Preparing to solve DNS-01
2022/03/20 17:34:26 [INFO] [*.example.de] acme: Cleaning DNS-01 challenge
2022/03/20 17:34:29 [WARN] [*.example.de] acme: cleaning up failed: inwx: (2200) Authentication error. Reason: (INVALID) The confirmation code is invalid.
2022/03/20 17:34:30 [INFO] Skipping deactivating of valid auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/12345
2022/03/20 17:34:30 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/12345
2022/03/20 17:34:30 Could not obtain certificates:
	error: one or more domains had a problem:
[*.example.de] [*.example.de] acme: error presenting token: inwx: (2200) Authentication error. Reason: (INVALID) The confirmation code is invalid.
```

</details>

### Go environment (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by gnoack**
This is a workaround for #1608.  INWX forbids to re-use the same TOTP twice, but the INWX DNS provider tries to reauthenticate from scratch on each step.

I believe that this is not easily implementable with the existing Lego DNS provider interface, so to avoid refactoring that interaction, let's just make the INWX provider wait a bit until a new token is available.  A new token is available every 30 seconds.

The current workaround is to invoke Lego many more times.  Retrying at a higher level is worse than retrying here.

Fixes #1608

### CODE REVIEW

**Review by ldez — COMMENTED** [review]
INWX API is weird.

Maybe we can decrease the 30s by reducing the validity period of the TOTP.

```go
	tan, err := totp.GenerateCodeCustom(d.config.SharedSecret, time.Now(), totp.ValidateOpts{
		Period:    10, // <-- the default is 30s
		Skew:      1,
		Digits:    otp.DigitsSix,
		Algorithm: otp.AlgorithmSHA1,
	})
```

**Comment by gnoack** [comment]
> INWX API is weird.
> 
> Maybe we can decrease the 30s by reducing the validity period of the TOTP.
> 
> ```go
> 	tan, err := totp.GenerateCodeCustom(d.config.SharedSecret, time.Now(), totp.ValidateOpts{
> 		Period:    10, // <-- the default is 30s
> 		Skew:      1,
> 		Digits:    otp.DigitsSix,
> 		Algorithm: otp.AlgorithmSHA1,
> 	})
> ```

This is a good idea, but unfortunately not possible.  The period is a system parameter, which the client ("prover") and server ("verifier") must agree on.  The TOTP QR code can specify the period, or it will be 30 seconds by default.

More mathematically speaking, the "counter" is derived by dividing the current Unix time in seconds by the period in seconds, rounding down.  If we made the period 10 instead of 30, we'd end up with counter values that are three times as high (and generate tokens which are valid roughly at epoch+3*(now-epoch), where epoch is Unix time 0).

So unfortunately, this idea does not work.

(Fun fact on the side, as I've been poking around in the RFC... it seems that by rejecting the second authentication with the same token value, INWX is actually following the RFC recommendation in the last paragraph of [RFC 6238, section 5.2](https://datatracker.ietf.org/doc/html/rfc6238#section-5.2).)

**Review by ldez — APPROVED** [review]
The fact of not being able to reuse the token is expected because it can be a major security issue.
This problem was my fault when I introduced the TOTP system, sometimes you were focusing on something and completely forgot the obvious :smile: 

I simplified the implementation and added tests to ease the maintenance.

Thank you for your work on this topic, your fix will benefit many users.

Offtopic: I closed (and reopened) the PR by error because I wanted to write something on another screen but I was still inside this page... (GitHub keyboard shortcuts + multiple screens = mistake)

File: providers/dns/inwx/inwx.go [hunk 1]
```diff
@@ -204,27 +204,34 @@ func (d *DNSProvider) twoFactorAuth(info *goinwx.LoginResponse) error {
...
-	d.prevTANCounter = tanCounter
+
+	d.previousCall = now
 
 	return d.client.Account.Unlock(tan)
 }
+
+func (d *DNSProvider) computeSleep(now time.Time) time.Duration {
+	if d.previousCall.IsZero() {
+		return 0 * time.Second
```
Comment (gnoack) [inline providers/dns/inwx/inwx.go:226]: I believe you could just write `return 0` here.  Integer literals can stand for any integer type, IIRC.

File: providers/dns/inwx/inwx.go [hunk 2]
```diff
@@ -204,27 +204,34 @@ func (d *DNSProvider) twoFactorAuth(info *goinwx.LoginResponse) error {
...
+	}
+
+	endPeriod := d.previousCall.Add(30 * time.Second)
+	if endPeriod.After(now) {
+		return endPeriod.Sub(now)
+	}
+
+	return 0 * time.Second
```
Comment (gnoack) [inline providers/dns/inwx/inwx.go:234]: ditto

File: providers/dns/inwx/inwx.go (hunk 1 above)
Comment (ldez) [reply providers/dns/inwx/inwx.go:226]: Yes, I know it is useless, it was just to use an explicit value as a kind of documentation.

File: providers/dns/inwx/inwx.go [hunk 3]
```diff
@@ -204,27 +204,34 @@ func (d *DNSProvider) twoFactorAuth(info *goinwx.LoginResponse) error {
...
 
 	return d.client.Account.Unlock(tan)
 }
+
+func (d *DNSProvider) computeSleep(now time.Time) time.Duration {
+	if d.previousCall.IsZero() {
+		return 0 * time.Second
+	}
+
+	endPeriod := d.previousCall.Add(30 * time.Second)
```
Comment (gnoack) [inline providers/dns/inwx/inwx.go]: While this works, I suspect we are wasting a few seconds here on average, because d.previousCall is never rooted to be a multiple of 30 seconds after the epoch (Unix time 0)?

It works though and how relevant this is depends a bit on the distance between ajacent TOTP attempts.

**Comment by gnoack** [comment]
Thank you @ldez for merging this - much appreciated, also for writing the tests, which I missed :)

I had a look at your patches and I think they work.  I left some minor comments - I think it is slowing the wait time down a few seconds more than the previous patch did, but I'll happily stand corrected if I am wrong here.  But it works anyway, and is an improvement over what this DNS provider did before.

File: providers/dns/inwx/inwx.go (hunk 3 above)
Comment (ldez) [reply providers/dns/inwx/inwx.go]: You are right, sorry I completely missed that.
Sorry, I will try to fix that.
I will truncate the previous time by 30 seconds.
