### PR TITLE
selectelv2: add missing options

### LINKED ISSUE #2638: selectelv2: some of the required options are not set
### Welcome

- [x] Yes, I'm using a binary release within 2 latest releases.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

When I run DNS challenge with Select v2 provider I expect to see somthing like this:

```
l[some.example.domain] acme: Obtaining bundled SAN certificate
[some.example.domain] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/2645193031/580043416161
[some.example.domain] acme: use dns-01 solver
[some.example.domain] acme: Preparing to solve DNS-01
 acme: Trying to solve DNS-01
[some.example.domain]acme: Checking DNS record propagation. [nameservers=127.0.0.11:53]
Wait for propagation [timeout: 1h0m0s, interval: 10m0s]
[some.example.domain] The server validated our request
[some.example.domain] acme: Cleaning DNS-01 challenge
[some.example.domain] acme: Validations succeeded; requesting certificates
[some.example.domain] Server responded with a certificate.
```

### What did you see instead?

After PR [#2523](https://github.com/go-acme/lego/pull/2523/files) in [v4.24](https://github.com/go-acme/lego/milestone/53) I suppose the DNS challenge for Selectel v2 provider was broken (see logs).

I suppose the reason in this [commit](https://github.com/selectel/go-selvpcclient/commit/4760293477c8a96033698218355af624a901371a#diff-c7a8497a8464aea112a0e4875c5072282006681c66069575cba0767bf337d87b) in the [go-selvpcclient](https://github.com/selectel/go-selvpcclient): they made this options required, but they are not passed in ClientOptions() func in this [file](https://github.com/go-acme/lego/blob/master/providers/dns/selectelv2/selectelv2.go).

### How do you use lego?

Docker image

### Reproduction steps

1. Install lego goacme/lego:v4.24 or higer.
2. Run command lego --dns=selectelv2 --domains=some.example.domain --accept-tos run

### Effective version of lego

```console
lego version 4.23.1 linux/amd64
```

### Logs

<details>

```console
11:00:18 [INFO] [*.some.example.domain.com] acme: Obtaining bundled SAN certificate
11:00:19 [INFO] [*.some.example.domain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/2645170821/580042096151
11:00:19 [INFO] [*.some.example.domain.com] acme: use dns-01 solver
11:00:19 [INFO] [*.some.example.domain.com] acme: Preparing to solve DNS-01
11:00:19 [INFO] [*.some.example.domain.com] acme: Cleaning DNS-01 challenge
11:00:19 [WARN] [*.some.example.domain.com] acme: cleaning up failed: selectelv2: authorize: new VPC client: validation error: some of the required options are not set: DomainName, AuthURL, AuthRegion 
11:00:19 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz/2645170821/580042096151
11:00:20 Could not obtain certificates:
	error: one or more domains had a problem:
	| [*.some.example.domain.com] [*.some.example.domain.com] acme: error presenting token: selectelv2: authorize: new VPC client: validation error: some of the required options are not set: DomainName, AuthURL, AuthRegion
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

### PR DESCRIPTION
**Pull request by ldez**
Fixes #2638

### CODE REVIEW

File: providers/dns/selectelv2/selectelv2.go [hunk 1]
```diff
@@ -235,12 +248,15 @@ func (d *DNSProvider) authorize() (*clientWrapper, error) {
...
 
-func obtainOpenstackToken(config *Config) (string, error) {
+func obtainOpenstackToken(ctx context.Context, config *Config) (string, error) {
 	vpcClient, err := selvpcclient.NewClient(&selvpcclient.ClientOptions{
-		Username:       config.Username,
-		Password:       config.Password,
-		UserDomainName: config.Account,
-		ProjectID:      config.ProjectID,
+		Context:    ctx,
+		DomainName: config.Account,
```
Comment (num213) [inline providers/dns/selectelv2/selectelv2.go:254]: I'm not sure about this change (actually because not knowing exactly in which cases someone is passing `DomainName` and `UserDomainName` with different values), but it seems that with this change there will be no option to pass `UserDomainName` directly through env vars.

p.s. I suppose that `UserDomainName` used in cases when we need to pass Selectel Account for users that were created and assigned a role in a different account.
