### PR TITLE
hurricane: only treat first word of response body as response code

### LINKED ISSUE #1408: hurricane: nochg response incorrectly interpreted as server error
- [x] Yes, I'm using a binary release within 2 latest releases.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

lego correctly handling the case in which the given dns-01 challenge token is already the value of the relevant TXT record on he.net's DNS servers.

### What did you see instead?

lego outputs the following (domain name and ACME account data redacted):

```
2021/05/23 20:39:02 [INFO] [...] acme: Obtaining bundled SAN certificate
2021/05/23 20:39:03 [INFO] [...] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/[...]
2021/05/23 20:39:03 [INFO] [...] acme: Could not find solver for: tls-alpn-01
2021/05/23 20:39:03 [INFO] [...] acme: Could not find solver for: http-01
2021/05/23 20:39:03 [INFO] [...] acme: use dns-01 solver
2021/05/23 20:39:03 [INFO] [...] acme: Preparing to solve DNS-01
2021/05/23 20:39:04 [INFO] [...] acme: Cleaning DNS-01 challenge
2021/05/23 20:39:04 [WARN] [...] acme: cleaning up failed: hurricane: Post "https://dyn.dns.he.net/nic/update": EOF
2021/05/23 20:39:04 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/[...]
2021/05/23 20:39:05 Could not obtain certificates:
        error: one or more domains had a problem:
[...] [...] acme: error presenting token: hurricane: attempt to change TXT record _acme-challenge.[...] returned nochg "PeBwwj6VsqoP4Y_eUJrSGWi0yNN614vYteNLBTpWfXk"
```

### Steps to reproduce

1. Use the `hurricane` DNS provider to solve a dns-01 challenge.
2. Simulate a failure before the TXT record update is verified (e.g. by killing the lego process).
3. Repeat step 1.

### Details

The `hurricane` DNS provider doesn't correctly handle the case in which the given challenge token is already the value of the relevant TXT record on he.net's DNS servers; this could happen, for instance, if an earlier lego run was aborted early because of a problem during the challenge. This is because he.net responds to the later request with the body

```
nochg "<challenge token>"
```

but the client in the `hurricane` DNS provider only expects to see

```
nochg
```

in this situation. The reflection of the challenge token causes the client to incorrectly interpret the response as a server error.

### PR DESCRIPTION
**Pull request by chrisnovakovic**
In the hurricane DNS provider, consider only the first word in the response body to be the response code when checking whether the request succeeded; specifically, do not necessarily consider multi-word responses to be indicative of server errors. This corrects the handling of `nochg` responses from he.net's Dynamic DNS service, in which the response code is followed by the unchanged value of the TXT record.

Fixes #1408

----

I've confirmed that this fixes the issue raised in #1408 (domain name redacted):

```
2021/05/23 21:02:01 [INFO] [...] acme: use dns-01 solver
2021/05/23 21:02:01 [INFO] [...] acme: Preparing to solve DNS-01
2021/05/23 21:02:01 nochg "PeBwwj6VsqoP4Y_eUJrSGWi0yNN614vYteNLBTpWfXk": unchanged content written to TXT record _acme-challenge.[...]
2021/05/23 21:02:01 [INFO] [...] acme: Trying to solve DNS-01
2021/05/23 21:02:01 [INFO] [...] acme: Checking DNS record propagation using [ns1.he.net:53]
2021/05/23 21:02:31 [INFO] Wait for propagation [timeout: 5m0s, interval: 30s]
2021/05/23 21:02:35 [INFO] [...] The server validated our request
2021/05/23 21:02:35 [INFO] [...] acme: Cleaning DNS-01 challenge
2021/05/23 21:02:35 [INFO] [...] acme: Validations succeeded; requesting certificates
2021/05/23 21:02:42 [INFO] [...] Server responded with a certificate.
```

### CODE REVIEW

**Comment by chrisnovakovic** [comment]
I'm unsure why the coverage tests are failing here, sorry. Is there something I need to fix in my PR?

File: providers/dns/hurricane/internal/client.go [hunk 1]
```diff
@@ -80,7 +81,12 @@ func (c *Client) UpdateTxtRecord(domain string, txt string) error {
 }
 
 func evaluateBody(body string, hostname string) error {
-	switch body {
+	words := strings.SplitN(body, " ", 2)
+	if len(words) == 0 {
+		return fmt.Errorf("attempt to change TXT record %s returned invalid body: %s", hostname, body)
+	}
```
Comment (ldez) [inline providers/dns/hurricane/internal/client.go:87]:
```suggestion
```

This check is useless, it's impossible to get a length of 0 with a `SplitN`:
https://play.golang.org/p/4UqWWI2lgDq

**Review by ldez — CHANGES_REQUESTED** [review]

**Review by ldez — APPROVED** [review]
Thanks

File: providers/dns/hurricane/internal/client.go (hunk 1 above)
Comment (chrisnovakovic) [reply providers/dns/hurricane/internal/client.go]: Nice spot, thanks!
