### PR TITLE
Increase INWX propagation timeout to 360s to improve robustness

### LINKED ISSUE #1297: DNS provider INWX randomly failing / inwx 2002
I am trying to use the DNS provider inwx.de

Usually using it with traefik, which repeatedly causes the inwx issue `'2002' Command error`, which is sent by INWX if a command is send after a logout. I suspect some race conditions if multiple domains are handled via traefik.

For debugging purposes, I tried using the CLI which also fails somewhat randomly:

The CLI command I use is:
```
lego --email="admin@mydomain.de" --server=https://acme-staging-v02.api.letsencrypt.org/directory --domains=mydomain.de --dns="inwx" run
```
or even
```
lego --email="admin@mydomain.de" --server=https://acme-staging-v02.api.letsencrypt.org/directory --domains=mydomain.de --dns="inwx" --dns.resolvers=8.8.8.8 --dns.disable-cp run
```

which works in 5% of the cases, but often enough it does not.

Often the DNS propagation does not seem to work. It runs into the 60s timeout or even detects the wrong token as the TXT record. Any advice on how I could debug this further and improve the INWX support?

Related to https://github.com/traefik/traefik/issues/6989

### PR DESCRIPTION
**Pull request by dragetd**
INWX has rather unstable propagation delays. Users reported that the
robustness of the DNS challenge improves with a longer timeout, thus instead
of using the default, hardcode a larger default. Six minutes seems to work
fine so far.

Fixes #1297

### CODE REVIEW

**Comment by dragetd** [comment]
I was not sure if you want a note in the documentation that the timeout is larger than usual. Tell me if I should change it. :-)

File: providers/dns/inwx/inwx.go [hunk 1]
```diff
@@ -42,7 +42,8 @@ type Config struct {
 func NewDefaultConfig() *Config {
 	return &Config{
 		TTL:                env.GetOrDefaultInt(EnvTTL, 300),
-		PropagationTimeout: env.GetOrDefaultSecond(EnvPropagationTimeout, dns01.DefaultPropagationTimeout),
+		// INWX has rather unstable propagation delays, thus using a larger default value
+		PropagationTimeout: env.GetOrDefaultSecond(EnvPropagationTimeout, 360),
```
Comment (ldez) [inline providers/dns/inwx/inwx.go:46]:
```suggestion
		PropagationTimeout: env.GetOrDefaultSecond(EnvPropagationTimeout, 360*time.Second),
```

**Review by ldez — CHANGES_REQUESTED** [review]
Hello, as your PR comes from a GitHub organization, I'm not able to commit on it.

So could you run `make generate-dns` and commit the result and rebase your PR.

Using a GitHub organization to handle forks is something that can be an issue with bots/automation, I can understand your approach but you have to know the constraints and that can cause problems to open source projects.

**Comment by dragetd** [comment]
Uh, I did not know this! How annoying! x.x Well, they added repository-typo filters and by default no longer show forks, it did improve ever since I made this construct. I guess it is time to clean it up!

Sorry for the hassle. :-(

I included your change and the updated documentation, rebased and squashed the changes.

**Review by ldez — APPROVED** [review]
Thanks :+1:

**Review by ldez — CHANGES_REQUESTED** [review]
Could you run format the source code (gofmt) ? thank you

**Review by ldez — APPROVED** [review]

**Comment by dragetd** [comment]
I am sorry for all the hassle :( and I am also nuking my organizations now!
