### PR TITLE
fix: rewrite status management

### LINKED ISSUE #2427: Nil pointer in error interface in checkOrderStatus
### Welcome

- [x] Yes, I'm using a binary release within 2 latest releases.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Rate limit error should not rise an exception

### What did you see instead?

Panic, nil pointer dereference. I will try to reproduce it later on, so far it can be emulated (based on discussion here: https://github.com/go-acme/lego/pull/2426)

### How do you use lego?

Library

### Reproduction steps

See https://go.dev/play/p/WQWmhF8yF8N

### Version of lego

```console
v4.21.0
```

### Logs

<details>

```console
panic: value method main.ProblemDetails.Error called using nil *ProblemDetails pointer

goroutine 1 [running]:
main.(*ProblemDetails).Error(0x4e169f?)
	<autogenerated>:1 +0x26
main.main()
	/tmp/sandbox1881138421/prog.go:70 +0x131
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

### PR DESCRIPTION
**Pull request by ldez**
Fixes #2427

### CODE REVIEW

File: acme/commons.go [hunk 1]
```diff
@@ -200,6 +200,14 @@ type Order struct {
 	Replaces string `json:"replaces,omitempty"`
 }
 
+func (r *Order) Err() error {
+	if r.Error != nil {
```
Comment (dmke) [inline acme/commons.go:204]: This method doesn't do anything useful. The expression `r.Error != nil ? r.Error : nil` can be condensed to just `r.Error`.

Do you want to add a nil check on `r`, i.e.

```suggestion
	if r != nil {
}
```

which would avoid a panic? https://go.dev/play/p/e9z35S2ydbu

File: acme/commons.go [hunk 2]
```diff
@@ -285,6 +293,14 @@ type Challenge struct {
 	KeyAuthorization string `json:"keyAuthorization"`
 }
 
+func (c *Challenge) Err() error {
+	if c.Error != nil {
```
Comment (dmke) [inline acme/commons.go:297]: Same here :)

```suggestion
	if c != nil {
```

**Review by dmke — CHANGES_REQUESTED** [review]

File: acme/commons.go (hunk 1 above)
Comment (ldez) [reply acme/commons.go:204]: You missed the point: the panic doesn't happen because the order is nil, but because `Error` is nil.

> This method doesn't do anything useful.

This method is doing something useful.

File: acme/commons.go (hunk 2 above)
Comment (ldez) [reply acme/commons.go:297]: Same here too.

**Comment by ldez** [comment]
I rewrote the status management because the root of the problem is not a nil pointer, but the fact that `invalid` status can be associated with a nil error.

Also, I updated the PR with tests.

File: acme/commons.go (hunk 1 above)
Comment (dmke) [reply acme/commons.go:204]: >> This method doesn't do anything useful.
>
> This method is doing something useful.

It's not being used though, how can it be useful?

I have locally removed the `(*Order) Err()` and `(*Challenge) Err()` methods, and tests still pass.

> https://go.dev/play/p/9X_m55Un5fI

That's surprising :thinking:

Comment (dmke) [reply acme/commons.go:204]: >>  I have locally removed the (*Order) Err() and (*Challenge) Err() methods, and tests still pass.
>
> I added a new commit yesterday, so yes, now they are unused but this is not the question.

Ah, I didn't catch that! That explains a lot :)

**Review by dmke — APPROVED** [review]
