### PR TITLE
cloudxns: provider deprecation

### LINKED ISSUE #2323: Remove CloudXNS DNS provider
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

The CloudXNS DNS provider has shut down. They [ended all free service in 2019](https://github.com/certbot/certbot/issues/7276) and then shut down. Their website is now a domain name seller parking page.

lego should remove the DNS provider from the supported providers and the code that interacts with their API

### What did you see instead?

<details>

image

</details>

### How do you use lego?

Binary

### Reproduction steps

1. Browse to the lego doc page : https://go-acme.github.io/lego/dns/cloudxns/
2. Click API documentation

You should be taken to a working DNS provider but instead are taken to a "buy this domain" page

### Version of lego

```console
lego version 4.19.2 linux/amd64
```

### Logs

N/A

### Go environment (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by ldez**
Fixes #2323

### CODE REVIEW

**Review by dmke — CHANGES_REQUESTED** [review]
May I propose a more radical approach where `cloudxns` will be reduced to something like

```go
// keep consts, type Config, and type DNSProvider

var ErrDeadProvider = errors.New("cloudxns: provider has shut down")

func NewDNSProvider() (*DNSProvider, error) {
    return nil, ErrDeadProvider
}

func NewDNSProviderConfig(*Config) (*DNSProvider, error) {
    return nil, ErrDeadProvider
}

func (d *DNSProvider) Present(string, string, string) error {
    return ErrDeadProvider
}

func (d *DNSProvider) CleanUp(string, string, string) error {
    return ErrDeadProvider
}
```

When their website/domain is already offline, I don't see why we need to keep any code for it.

This way, users get an early and explicit reason ("provider has shut down" vs. "Get <URL>: context deadline exceeded")

File: providers/dns/cloudxns/cloudxns.go [hunk 1]
```diff
@@ -2,28 +2,11 @@
...
-const (
-	envNamespace = "CLOUDXNS_"
-
-	EnvAPIKey    = envNamespace + "API_KEY"
-	EnvSecretKey = envNamespace + "SECRET_KEY"
-
-	EnvTTL                = envNamespace + "TTL"
-	EnvPropagationTimeout = envNamespace + "PROPAGATION_TIMEOUT"
-	EnvPollingInterval    = envNamespace + "POLLING_INTERVAL"
-	EnvHTTPTimeout        = envNamespace + "HTTP_TIMEOUT"
```
Comment (dmke) [inline providers/dns/cloudxns/cloudxns.go:26]: Removing these would be a breaking change, let's keep them for now.

**Review by dmke — CHANGES_REQUESTED** [review]

**Review by dmke — APPROVED** [review]
